config/routes.rb
Gera::Engine.routes.draw do
  root 'direction_rates#index'
  resources :payment_systems

  resources :currency_rate_history_intervals, only: [:index]
  resources :direction_rate_history_intervals, only: [:index]

  resources :currencies, only: [:index]
  resources :direction_rates do
    member do
      get :last
    end
  end
  resources :external_rates, only: [:index, :show]

  resources :exchange_rates, only: [:show] do
    member do
      get :details
    end
  end
  resources :external_rate_snapshots, only: [:index, :show]
  resources :currency_rates
  resources :currency_rate_modes, only: [:edit, :update, :new, :create]
  resources :currency_rate_mode_snapshots, only: [:index, :edit, :update, :show, :create] do
    member do
      post :activate
    end
  end
  resources :rate_sources
end

app/models/concerns/gera/currency_pair_generator.rb
# frozen_string_literal: true

module Gera
  module CurrencyPairGenerator
    def generate_pairs_from_currencies(currencies)
      currencies = currencies.map { |c| Money::Currency.find c }

      currencies
        .map { |c1| currencies.reject { |c2| c2 == c1 }.map { |c2| [c1, c2].join('/') } }
        .flatten.compact
        .map { |cp| Gera::CurrencyPair.new cp }.uniq
    end
  end
end

app/models/concerns/gera/currency_pair_support.rb
# frozen_string_literal: true

module Gera
  module CurrencyPairSupport
    extend ActiveSupport::Concern

    included do
      if ancestors.include? ActiveRecord::Base
        scope :by_currency_pair, ->(pair) { where cur_from: pair.cur_from.to_s, cur_to: pair.cur_to.to_s }

        def self.find_by_currency_pair(pair)
          by_currency_pair(pair).take
        end

        def self.find_or_build_by_currency_pair(pair)
          by_currency_pair(pair).take || new(currency_pair: pair)
        end
      end
    end

    def currency_pair=(value)
      self.cur_from = value.cur_from
      self.cur_to = value.cur_to
      @currency_pair = nil
      @currency_from = nil
      @currency_to = nil
      value
    end

    def currency_pair
      @currency_pair ||= Gera::CurrencyPair.new currency_from, currency_to
    end

    def currency_from
      @currency_from ||= cur_from.is_a?(Money::Currency) ? cur_from : Money::Currency.find!(cur_from)
    end

    def currency_to
      @currency_to ||= cur_to.is_a?(Money::Currency) ? cur_to : Money::Currency.find!(cur_to)
    end
  end
end

app/models/concerns/gera/currency_rate_mode_builder_support.rb
# frozen_string_literal: true

module Gera
  module CurrencyRateModeBuilderSupport
    def build_currency_rate
      @currency_rate ||= build_currency_rate!
    rescue CurrencyRateBuilder::Error => e
      Rails.logger.warn "[CurrencyRateModeBuilderSupport] Failed to build currency rate: #{e.message}"
      nil
    end

    def build_result
      @result ||= builder.build_currency_rate
    end

    def build_currency_rate!
      raise build_result.error if build_result.error?

      build_result.currency_rate
    end

    def builder
      case mode
      when 'auto'
        CurrencyRateAutoBuilder.new(currency_pair: currency_pair)
      when 'cross'
        CurrencyRateCrossBuilder.new(currency_pair: currency_pair, cross_rate_modes: cross_rate_modes)
      else
        source = RateSource.find_by_key(mode)
        raise "not supported mode #{mode} for #{currency_pair}" unless source.present?

        CurrencyRateDirectBuilder.new currency_pair: currency_pair, source: source
      end
    end
  end
end

app/models/concerns/gera/direction_support.rb
# frozen_string_literal: true

module Gera
  module DirectionSupport
    def direction=(value)
      self.payment_system_from = value.payment_system_from
      self.payment_system_to = value.payment_system_to
    end

    def direction
      ::Gera::Direction.new(ps_from: payment_system_from, ps_to: payment_system_to).freeze
    end
  end
end

app/models/concerns/gera/history_interval_concern.rb
# frozen_string_literal: true

module Gera
  module HistoryIntervalConcern
    extend ActiveSupport::Concern
    INTERVAL = 5.minutes

    included do
      extend AutoLogger::Named.new(name: 'history_intervals')
      before_save do
        self.avg_rate = (max_rate + min_rate) / 2.0
      end

      before_save do
        raise "Time must be even to #{INTERVAL}" unless interval_from.min % INTERVAL.parts[:minutes] == 0
        raise "Time must be even to #{INTERVAL}" unless interval_to.min % INTERVAL.parts[:minutes] == 0
        raise 'Time must have zero seconds' unless interval_from.sec == 0
        raise 'Time must have zero seconds' unless interval_to.sec == 0
      end

      before_save do
        raise "min_rate (#{min_rate}) must be less or equal to max_rate (#{max_rate})" if min_rate > max_rate
      end
    end

    class_methods do
      def create_multiple_intervals_from!(interval_from, interval_to = nil)
        interval_from -= interval_from.sec # Обнуляем секунды
        interval_from -= interval_from.min % INTERVAL.parts[:minutes]
        interval_to ||= Time.zone.now
        ((interval_to - interval_from) / 5.minutes).to_i.times do |i|
          f = interval_from + i * INTERVAL
          begin
            logger.info "#{self}: Create HistoryInterval #{f} -> #{f + INTERVAL}"
            transaction do
              create_by_interval! f, f + INTERVAL
            end
            logger.info "#{self}: Create HistoryInterval #{f} -> #{f + INTERVAL} - done"
          rescue ActiveRecord::RecordNotUnique => err
            logger.error err
          end
        end
      end
    end
  end
end

app/models/gera/application_record.rb
# frozen_string_literal: true

module Gera
  # @abstract
  class ApplicationRecord < ::ApplicationRecord
    self.abstract_class = true
  end
end

app/models/gera/cbr_external_rate.rb
# frozen_string_literal: true

module Gera
  class CbrExternalRate < ApplicationRecord
    before_save do
      raise 'нет значения' unless rate > 0
    end

    def <=>(other)
      rate <=> other.rate
    end
  end
end

app/models/gera/cross_rate_mode.rb
# frozen_string_literal: true

module Gera
  class CrossRateMode < ApplicationRecord
    include CurrencyPairSupport
    belongs_to :currency_rate_mode
    belongs_to :rate_source, optional: true

    def title
      "#{currency_pair}(#{rate_source || 'auto'})"
    end
  end
end

app/models/gera/currency_rate.rb
# frozen_string_literal: true

module Gera
  # Базовый курс
  # Basic currency rate
  class CurrencyRate < ApplicationRecord
    include CurrencyPairSupport
    include Authority::Abilities

    belongs_to :snapshot, class_name: 'Gera::CurrencyRateSnapshot'
    belongs_to :external_rate, optional: true
    belongs_to :rate_source, optional: true

    belongs_to :external_rate1, class_name: 'Gera::ExternalRate', optional: true
    belongs_to :external_rate2, class_name: 'Gera::ExternalRate', optional: true
    belongs_to :external_rate3, class_name: 'Gera::ExternalRate', optional: true

    has_many :direction_rates, class_name: 'Gera::DirectionRate'

    scope :by_exchange_rate, ->(er) { by_currency_pair er.currency_pair }

    enum :mode, %i[direct inverse same cross], prefix: true

    before_save do
      raise("У кросс-курса (#{currency_pair}) должен быть минимум 1 external_rates (#{external_rates.count})") if mode_cross? && external_rates.blank?

      self.metadata ||= {}
    end

    def external_rates=(rates)
      self.external_rate, self.external_rate1, self.external_rate2, self.external_rate3 = rates
    end

    def external_rates
      [external_rate, external_rate1, external_rate2, external_rate3].compact
    end

    def to_s
      currency_pair.to_s
    end

    def inspect
      "#{currency_pair}:#{humanized_rate}"
    end

    def in_money
      reverse_rate_money.to_d > 1 ? reverse_rate_money : 1
    end

    def out_money
      rate_money.to_d > 1 ? rate_money : 1
    end

    def rate_money
      Money.from_amount(rate_value, cur_to)
    end

    def reverse_rate_money
      Money.from_amount(1.0 / rate_value, cur_from)
    end

    def humanized_rate
      if rate_value < 1
        "#{rate_value} (1/#{1.0 / rate_value})"
      else
        rate_value
      end
    end

    def dump
      as_json(only: %i[created_at cur_from cur_to mode rate_value metadata rate_source_id]).merge external_rates: external_rates.map(&:dump)
    end

    def meta
      @meta ||= OpenStruct.new metadata.deep_symbolize_keys
    end
  end
end

app/models/gera/currency_rate_history_interval.rb
# frozen_string_literal: true

module Gera
  class CurrencyRateHistoryInterval < ApplicationRecord
    include HistoryIntervalConcern
    def self.create_by_interval!(interval_from, interval_to = nil)
      interval_to ||= interval_from + INTERVAL
      CurrencyRate
        .where('created_at >= ? and created_at < ?', interval_from, interval_to)
        .group(:cur_from, :cur_to)
        .pluck(:cur_from, :cur_to, 'min(rate_value)', 'max(rate_value)')
        .each do |cur_from, cur_to, min_rate, max_rate|

        next if cur_from == cur_to

        create!(
          cur_from_id: Money::Currency.find(cur_from).local_id,
          cur_to_id: Money::Currency.find(cur_to).local_id,
          min_rate: min_rate, max_rate: max_rate,
          interval_from: interval_from, interval_to: interval_to
        )
      end
    end
  end
end

app/models/gera/currency_rate_history_interval_filter.rb
# frozen_string_literal: true

module Gera
  class CurrencyRateHistoryIntervalFilter
    include Virtus.model strict: true
    include ActiveModel::Conversion
    extend  ActiveModel::Naming
    include ActiveModel::Validations

    attribute :cur_from, String, default: ->(_a, _b) { Money::Currency.first }
    attribute :cur_to, String, default: ->(_a, _b) { Money::Currency.first }
    attribute :value_type, String, default: 'rate'

    def currency_from
      Money::Currency.find cur_from
    end

    def currency_to
      Money::Currency.find cur_to
    end

    def to_param
      to_hash
    end

    def persisted?
      false
    end
  end
end

app/models/gera/currency_rate_mode.rb
# frozen_string_literal: true

module Gera
  class CurrencyRateMode < ApplicationRecord
    include CurrencyPairSupport
    include CurrencyRateModeBuilderSupport
    include Authority::Abilities

    belongs_to :snapshot, class_name: 'CurrencyRateModeSnapshot', foreign_key: :currency_rate_mode_snapshot_id
    has_many :cross_rate_modes

    # Тут режими из ключей rate_source
    # TODO выделить привязку к rate_source в отедельную ассоциацию
    enum :mode, %i[auto cbr cbr_avg exmo cross bitfinex], prefix: true

    accepts_nested_attributes_for :cross_rate_modes, reject_if: :all_blank, allow_destroy: true

    delegate :to_s, to: :mode

    def self.default_for_pair(pair)
      new(currency_pair: pair, mode: :auto)
    end

    def to_s
      new_record? && mode.auto? ? "default" : mode
    end

    def mode
      super.inquiry
    end
  end
end

app/models/gera/currency_rate_mode_snapshot.rb
# frozen_string_literal: true

module Gera
  class CurrencyRateModeSnapshot < ApplicationRecord
    has_many :currency_rate_modes, dependent: :destroy

    scope :ordered, -> { order('status desc').order('created_at desc') }

    enum :status, %i[draft active deactive], prefix: true

    accepts_nested_attributes_for :currency_rate_modes

    before_validation do
      self.title = Time.zone.now.to_s if title.blank?
    end

    validates :title, presence: true, uniqueness: { case_sensitive: false }

    def create_modes!
      CurrencyPair.all.each do |pair|
        currency_rate_modes.create! currency_pair: pair
      end
      self
    end
  end
end

app/models/gera/currency_rate_snapshot.rb
# frozen_string_literal: true

module Gera
  class CurrencyRateSnapshot < ApplicationRecord
    has_many :rates, class_name: 'Gera::CurrencyRate', foreign_key: :snapshot_id
    belongs_to :currency_rate_mode_snapshot

    def currency_rates
      rates
    end
  end
end

app/models/gera/direction.rb
# frozen_string_literal: true

module Gera
  # Exchange Direction
  #
  class Direction
    include Virtus.model

    attribute :ps_from # , PaymentSystem
    attribute :ps_to   # , PaymentSystem

    alias_attribute :payment_system_from, :ps_from
    alias_attribute :payment_system_to, :ps_to
    alias_attribute :income_payment_system, :ps_from
    alias_attribute :outcome_payment_system, :ps_to

    delegate :id, to: :ps_to, prefix: true
    delegate :id, to: :ps_from, prefix: true

    def currency_from
      payment_system_from.currency
    end

    def currency_to
      payment_system_to.currency
    end

    def inspect
      to_s
    end

    def to_s
      "direction:#{payment_system_from.try(:id) || '???'}-#{payment_system_to.try(:id) || '???'}"
    end

    def exchange_rate
      Universe.exchange_rates_repository.find_by_direction self
    end

    def direction_rate
      Universe.direction_rates_repository.find_by_direction self
    end
  end
end

app/models/gera/direction_rate.rb
# frozen_string_literal: true

module Gera
  # Конечный курс
  # Finite direction rate
  class DirectionRate < ApplicationRecord
    include Mathematic
    include AutoLogger
    include DirectionSupport
    include Authority::Abilities
    include AliasAssociation

    UnknownExchangeRate = Class.new StandardError

    belongs_to :ps_from, class_name: 'Gera::PaymentSystem'
    belongs_to :ps_to, class_name: 'Gera::PaymentSystem'
    belongs_to :currency_rate, class_name: 'Gera::CurrencyRate'
    belongs_to :exchange_rate
    belongs_to :snapshot, class_name: 'Gera::DirectionRateSnapshot'

    before_validation do
      self.ps_from = exchange_rate.payment_system_from
      self.ps_to = exchange_rate.payment_system_to
    end

    before_validation :calculate_rate, unless: :finite_rate

    validates :base_rate_value, presence: true
    validates :rate_percent, presence: true
    validates :finite_rate, presence: true

    alias_association :payment_system_from, :ps_from
    alias_association :payment_system_to, :ps_to
    alias_association :income_payment_system, :ps_from
    alias_association :outcome_payment_system, :ps_to
    alias_attribute :income_payment_system_id, :ps_from_id
    alias_attribute :outcome_payment_system_id, :ps_to_id

    alias_attribute :comission, :rate_percent
    alias_attribute :finite_rate, :rate_value

    def exchange(amount)
      rate.exchange amount, outcome_currency
    end

    def reverse_exchange(amount)
      rate.reverse_exchange amount, income_currency
    end

    def currency_pair
      @currency_pair ||= CurrencyPair.new income_currency, outcome_currency
    end

    def income_currency
      ps_from.currency
    end

    def outcome_currency
      ps_to.currency
    end

    def ps_comission
      ps_to.commission
    end

    def in_money
      return 1 if rate_value < 1

      rate_value
    end

    def out_money
      return 1.0 / rate_value if rate_value < 1

      1
    end

    def rate
      RateFromMultiplicator.new(rate_value).freeze
    end

    def rate_money
      Money.from_amount(rate_value, currency_rate.currency_to)
    end

    def base_rate
      RateFromMultiplicator.new(base_rate_value).freeze
    end

    def inverse_direction_rate
      Universe.direction_rates_repository.get_matrix[ps_to_id][ps_from_id]
    end

    def get_profit_result(income_amount)
      res = calculate_profits(
        base_rate: base_rate_value,
        comission: rate_percent,
        ps_interest: ps_comission,
        income_amount: income_amount
      )

      diff = res.finite_rate.to_f.as_percentage_of(rate_value.to_f) - 100

      logger.warn "direction_rate_id=#{id} Calculates finite rate (#{res.finite_rate}) does not equal to current (#{rate_value}). Difference is #{diff}" if diff.abs > 0

      res
    end

    def dump
      as_json(only: %i[id ps_from_id ps_to_id currency_rate_id rate_value base_rate_value rate_percent created_at])
        .merge currency_rate: currency_rate.dump, dump_version: 1
    end

    def exchange_notification
      by_income = ExchangeNotification.find_by(
        income_payment_system_id: income_payment_system_id,
        outcome_payment_system_id: nil
      )

      by_outcome = ExchangeNotification.find_by(
        income_payment_system_id: nil,
        outcome_payment_system_id: outcome_payment_system_id
      )

      return ExchangeNotification.new(
        income_payment_system_id: income_payment_system_id,
        outcome_payment_system_id: outcome_payment_system_id,
        body_ru: [by_income.body_ru, by_outcome.body_ru].join(' <br /><br /> '),
        body_en: [by_income.body_en, by_outcome.body_en].join(' <br /><br /> '),
        body_cs: [by_income.body_cs, by_outcome.body_cs].join(' <br /><br /> ')
      ) if by_income && by_outcome

      ExchangeNotification.find_by(
        income_payment_system_id: income_payment_system_id,
        outcome_payment_system_id: outcome_payment_system_id
      ) || by_income || by_outcome
    end

    def calculate_rate
      self.base_rate_value = currency_rate.rate_value
      raise UnknownExchangeRate, "No exchange_rate for #{ps_from}->#{ps_to}" unless exchange_rate

      self.rate_percent = exchange_rate.final_rate_percents
      self.rate_value = calculate_finite_rate base_rate_value, rate_percent unless rate_percent.nil?
    end
  end
end

app/models/gera/direction_rate_snapshot.rb
# frozen_string_literal: true

module Gera
  class DirectionRateSnapshot < ApplicationRecord
    has_many :direction_rates, foreign_key: :snapshot_id
  end
end

app/views/gera/application/_attributes_table.slim
table.table.table-condensed.table-narrow
  - columns.each do |column|
    tr
      th= object.class.attribute_title column
      td= object.send column

app/views/gera/application/_currencies_table.slim
- currencies ||= Money::Currency.all
- min_width ||= 80

.table-sticky-container
  table.table.table-condensed.table-narrow.text-right.table-cross
    thead.bg-white
      tr
        th.text-center colspan=currencies.count+1 Отдаем &rarr;
      tr
        th.text-nowrap Получаем &darr;
        - currencies.each do |cur|
          th.text-right style="min-width: #{min_width}px"= cur
    tbody
      - currencies.each do |cur2|
        tr
          th.text-right= cur2
          - currencies.each do |cur1|
            = yield Gera::CurrencyPair.new cur2, cur1

app/views/gera/application/_currency_rate_mode_snapshots.slim
= link_to 'Создать новый', currency_rate_mode_snapshots_path, method: :post, class: 'btn btn-success'
ul.nav.nav-pills.nav-stacked.m-t-lg
  - Gera::CurrencyRateModeSnapshot.ordered.each do |crms|
    = active_link_to currency_rate_mode_snapshot_path(crms), wrap_tag: :li, active: current_snapshot == crms do 
      = crms.title
      span.m-l-md= crms_status_label crms.status

app/views/gera/application/_direction_rate.slim
- object = Gera::DirectionRateDecorator.decorate (direction_rate)

h2= t '.title', id: direction_rate.id
- columns = %i(direction inverse_direction created_at base_rate_value rate_percent ps_comission rate_value)

= render 'attributes_table', object: object, columns: columns

app/views/gera/application/_directions_submenu.slim
h1.m-b-md Управление обменом
hr
ul.nav.nav-tabs
    -# TODO
    -# = active_link_to 'Управление обменом', operator_exchange_managers_url, wrap_tag: :li
    - if Gera::DirectionRate.readable_by? current_user
      = active_link_to 'Конечные курсы', direction_rates_url, wrap_tag: :li, active: controller_name == 'direction_rates' && action_name == 'index'

    -# TODO minimals
    /- if Gera::DirectionRate.readable_by? current_user
      /= active_link_to 'Минималки', minimals_direction_rates_url, wrap_tag: :li, active: controller_name == 'direction_rates' && action_name == 'minimals'

app/views/gera/application/_directions_table.slim
.container-scrollable
  .table-sticky-container
    table.table-condensed.table-comission.table-cross.table-bordered.table-directions
      thead.bg-white
        tr
          th
          - payment_systems.each do |ps_to|
            th.text-center title="(#{ps_to.id}) #{ps_to.name}"
              = ps_icon ps_to
      tbody
        - payment_systems.each do |ps_from|
          tr
            th.text-center title="(#{ps_from.id}) #{ps_from.name}"= ps_icon ps_from
            - payment_systems.each do |ps_to|
              = yield Gera::Direction.new(ps_from: ps_from, ps_to: ps_to).freeze

app/views/gera/application/_exchange_rate.slim
- object = ExchangeRateDecorator.decorate exchange_rate

h2 Курс направления (#{object.title})
- columns = %i(id comission_percents)

= render 'attributes_table', object: object, columns: columns

app/views/gera/application/_external_rate.slim
- object = ExternalRateDecorator.decorate external_rate

h2 Внешний курс (#{object.title})
- columns = %i(id snapshot created_at source sell_price buy_price)

= render 'attributes_table', object: object, columns: columns

app/views/gera/application/_header.slim
= render 'topnav' do
  = active_link_to 'Базовый курс', currency_rates_path, wrap_tag: :li
  = active_link_to 'Конечный курс', direction_rates_path, wrap_tag: :li
  li.dropdown
    = link_to '#', class: 'dropdown-toggle', data: { toggle: :dropdown }, role: :button, 'aria-haspopup' => true, 'aria-expanded' => false do
      | Настройки
      .m-l-sm.span.caret
    ul.dropdown-menu
      = active_link_to 'Валюты', currencies_path, wrap_tag: :li
      = active_link_to 'Платежные системы', payment_systems_path, wrap_tag: :li
      = active_link_to 'Методы расчета', currency_rate_mode_snapshots_path, wrap_tag: :li
      = active_link_to 'Источники курсов', rate_sources_path, wrap_tag: :li

app/views/gera/application/_table.slim
- allow_edit = false unless defined? :allow_edit
- parent = nil unless defined? :parent
- if scope.empty?
  p.text-info Пусто
- else
  .table-sticky-container
    table.table.table-condensed.table-striped.table-narrow
      thead.bg-white
        tr
          - columns.each do |column|
            th title=column
              = decorator_class.attribute_title column
              - if params[:show_attribute]
                br
                code.text-small= column
      tbody
        - scope.each do |record|
          - decorated = decorator_class.decorate record
          tr class=decorated.try(:row_class)
            - columns.each do |column|
              td class=(decorated.try(:column_class, column) || 'text-nowrap')
                - if allow_edit && allow_edit_column?(record, column)
                  - value = record.send column
                  = smart_best_in_place [namespace, parent, decorated].compact, column, value
                - else
                  = decorated.send column

  = paginate scope if scope.respond_to? :total_pages

app/views/gera/application/_topnav.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to app_title, root_path, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        = yield

      - if logged_in?
        ul.nav.navbar-nav.navbar-right
          li.dropdown
            = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }, role: :button, 'aria-haspopup' => true, 'aria-expanded' => false do
              = ion_icon :user, text: current_user.email
              .m-l-sm.span.caret
            ul.dropdown-menu
              li= link_to t('.exit'), main_app.sessions_path, method: :delete

app/views/gera/application/direction_details.slim
- ps_from = direction.ps_from
- ps_to = direction.ps_to
- exchange_rate = direction.exchange_rate
- direction_rate = direction.direction_rate
.row
  .col-md-3
    dl
      dt Конечный курс
      dd= rate_humanized_description(direction_rate.rate_value, ps_from.currency, ps_to.currency)
      dt Направление
      dd
        = direction_with_icons direction
      dt Статус
      dd
        - if exchange_rate.is_enabled?
          .label.label-success Включено
        - else
          .label.label-default Отключено

    /- if legacy_rate.present?
      /dt В пыхе
      /= rate_humanized_description(legacy_rate, ps_from.currency, ps_to.currency)

  .col-md-3
    dl
      dt Базовый курс 
      dd= rate_humanized_description direction_rate.base_rate_value, ps_from.currency, ps_to.currency
      dt Комиссия 
      dd= '%.3f%' % direction_rate.rate_percent

      dt Обратный конечный курс: #{direction_with_icons direction_rate.inverse_direction_rate}
      dd= rate_humanized_description(direction_rate.inverse_direction_rate.rate_value, ps_from.currency, ps_to.currency)
  .col-md-3
    - status = BestChangeService.new( exchange_rate: exchange_rate ).status
    dt
      dt На bestchange.ru
      - if status.present?
        dd
          span.m-r-md = '%.3f%' % status.bestchange_base_percent_rate
          - if status.state == BestChangeStatus::STATE_ACTUAL
            span.label.label.success OK
          - else
            span.label.label-danger Комиссия отличается (#{status.state})
        =
        dt Позиция
        dd= status.position + 1
        dt Курс
        dd= status.finite_rate
      - else
        dd
          span.label.label-warning В списке отсутствует
  .col-md-3
    dl
      dt Публичные резервы
      dd= humanized_money_with_currency ps_to.reserve_amount

      dt Минимальная сумма на обмен (расчет)
      dd= humanized_money_with_currency direction_rate.minimal_income_amount

      dt Максимальная сумма на обмен (расчет)
      dd= humanized_money_with_currency direction_rate.maximal_income_amount

      /dt Минималка на прием (#{direction.currency_from})
      /dd
        /= humanized_money_with_currency direction.minimal_income_amount
        /span.m-l-md= "(#{humanized_money_with_currency direction.minimal_income_amount.exchange_to(direction.currency_to)})".html_safe

      /dt Минималка на отдачу (#{direction.currency_to})
      /dd
        /= humanized_money_with_currency direction.minimal_out_amount
        /span.m-l-md= "(#{humanized_money_with_currency direction.minimal_out_amount.exchange_to(direction.currency_from)})".html_safe


    
div.text-small.text-muted Расчет за #{l direction_rate.created_at, format: :long}, direction_rate_snapshot_id=#{Gera::Universe.direction_rates_repository.snapshot.id}

app/views/gera/application/page.html.slim
p= message